# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db8e16fb1199bc3ccdf720537d478b25327c47921268722c416767bde32f95e2aa0d93672252558db42b2ac0292df4d31abb6d69e54c886856d8fb5fcfbf2c4

test:
  secret_key_base: 2269145a834f2336e7953eba3d69eba191c13c9765b8c61e1c4f5c2561caf27038938b47c2163ef56b3045ca9a265c32a792de6d85a05da1b2c238fa9b1360f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
